[package]
name = "brainrot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
phf = "0.11.3"
phf_macros = "0.11.3"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "2.0.11"
